### PR TITLE
update prettier

### PR DESCRIPTION
**Pull request by epicallan**
- Change Babylon parser to Babel

### CODE REVIEW

**Comment by gcanti** [comment]
Thanks @epicallan. Sorry but I'm afraid I can't maintain this package anymore. Also I get the following error while installing `pulp`

```
npm install -g purescript bower pulp

> install-purescript --purs-ver=0.12.5

✖ Check if a prebuilt 0.12.5 binary is provided for macOS (26s)
  Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com
▬ Download the prebuilt PureScript binary
▬ Verify the prebuilt binary works correctly
▬ Save the downloaded binary to the npm cache directory
```

I may transfer the ownership of this repo to you if you are willing to maintain it.

**Comment by epicallan** [comment]
@gcanti I am fine with maintaining, so please transfer ownership. Thanks 

I am also not sure why you are getting above error.

**Comment by gcanti** [comment]
> I am fine with maintaining, so please transfer ownership

Thanks! Please remove your repo `epicallan/purescript-prettier` otherwise I can't transfer the ownership

**Comment by epicallan** [comment]
Done. I have removed it.

**Pull request merged**
